#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: psachin.github.io

# Short bio or description (displayed in the header)
description: Emacser

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://s.gravatar.com/avatar/7cf56d80d5fd30fa736647c22b751784?s=80

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: iclcoolster@gmail.com
  facebook:
  flickr:
  github: psachin
  gitlab: psachin
  instagram:
  linkedin:
  pinterest:
  rss: hooya # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/iclcoolsterU
  googleplus: u/0/+Sachinp

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: darkstar

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-45506609-3

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://psachin.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

authors:
  sachin:
    name: Sachin Patil
    display_name: Sachin
    gravatar: 7cf56d80d5fd30fa736647c22b751784?s=80
    email: iclcoolster@gmail.com
    web: http://psachin.github.io
    twitter:
    github: psachin

#
# !! You don't need to change any of the configuration flags below !!
#

version: v1.1.0
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
